module.exports = {
  apps: [
    {
      name: 'auth-service',
      cwd: './apps/auth-service',
      script: 'dist/main.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/auth-error.log',
      out_file: './logs/auth-out.log',
      merge_logs: true,
    },
    {
      name: 'listing-service',
      cwd: './apps/listing-service',
      script: 'dist/main.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/listing-error.log',
      out_file: './logs/listing-out.log',
      merge_logs: true,
    },
    {
      name: 'chat-service',
      cwd: './apps/chat-service',
      script: 'dist/main.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/chat-error.log',
      out_file: './logs/chat-out.log',
      merge_logs: true,
    },
    {
      name: 'payment-service',
      cwd: './apps/payment-service',
      script: 'dist/main.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/payment-error.log',
      out_file: './logs/payment-out.log',
      merge_logs: true,
    },
    {
      name: 'notification-service',
      cwd: './apps/notification-service',
      script: 'dist/main.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      max_memory_restart: '200M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/notification-error.log',
      out_file: './logs/notification-out.log',
      merge_logs: true,
    },
    {
      name: 'admin-service',
      cwd: './apps/admin-service',
      script: 'dist/main.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      max_memory_restart: '200M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/admin-error.log',
      out_file: './logs/admin-out.log',
      merge_logs: true,
    },
    {
      name: 'api-gateway',
      cwd: './apps/api-gateway',
      script: 'dist/main.js',
      instances: 1,
      env: { NODE_ENV: 'production' },
      max_memory_restart: '300M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/gateway-error.log',
      out_file: './logs/gateway-out.log',
      merge_logs: true,
      wait_ready: true,
      listen_timeout: 10000,
    },
    {
      name: 'web',
      cwd: './apps/web',
      script: 'node_modules/.bin/next',
      args: 'start',
      instances: 1,
      env: { NODE_ENV: 'production', PORT: '3000' },
      max_memory_restart: '500M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: './logs/web-error.log',
      out_file: './logs/web-out.log',
      merge_logs: true,
    },
  ],
};
